// Generate docs/COOLING-LOOP-MBSE.md — the engineering and integration report — from the model and the recorded evidence.
// node scripts/report-mbse.mjs > docs/COOLING-LOOP-MBSE.md
import { readFile } from 'node:fs/promises';
import { study, limitText } from '../src/engineering/evaluate.js';
import { REQUIREMENTS, LOOP_A, ASSUMPTIONS, EQUATIONS, BOUNDARY, LIMITS, SYSTEM, INTERFACES, FLUIDS, CONTEXT } from '../src/engineering/cooling-system.js';

const ix = JSON.parse(await readFile(new URL('../evidence/cameo/index.json', import.meta.url), 'utf8'));
const st = study();
const r1 = v => (Math.round(v * 10) / 10).toFixed(1);
const int = v => Math.round(v).toLocaleString('en-US');
const L = [];
const p = (...a) => L.push(...a);
const table = (head, rows) => { p(`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map(r => `| ${r.join(' | ')} |`), ''); };

p('# Cooling Loop A — MBSE evolution (branch `cooling-loop-mbse`)', '',
  '> GEN7 recognised when an operational problem became an engineering problem, formulated the engineering question, connected to the authoritative MBSE environment (CATIA Magic through cameo-mcp-bridge), evaluated the current architecture and a proposed evolution under identical conditions, and brought traceable evidence back to a human decision.', '',
  '*Generated by `node scripts/report-mbse.mjs` from `src/engineering` and `evidence/cameo/index.json`. Demonstration case — not a real facility.*', '');

p('## 1. Cameo environment (verified live through the bridge)', '');
table(['Item', 'Value', 'How it was verified'], [
  ['Product', `${ix.environment.product} ${ix.environment.release}`, ix.environment.releaseSource],
  ['Project', ix.environment.project, '`cameo_get_project`'],
  ['Cameo MCP Bridge', `plugin ${ix.bridge.version} · API ${ix.bridge.api} · handshake ${ix.bridge.handshake} · healthy: ${ix.bridge.healthy}`, '`cameo_status`, `cameo_get_capabilities`'],
  ['MCP server', `${ix.bridge.mcpServer.name} · ${ix.bridge.mcpTools} tools · protocol ${ix.bridge.mcpServer.protocolVersion}`, 'MCP `initialize` + `tools/list`'],
  ['SysML', `${ix.environment.sysml.version} — plugin ${ix.environment.sysml.plugin.version}`, 'plugin list read in the Cameo JVM (`cameo_execute_macro`, read-only)'],
  ['SysML v2 plugin', ix.environment.sysml.sysmlV2Installed ? 'installed' : 'not installed', 'plugin list'],
  ['Simulation Toolkit', ix.environment.simulation.available ? 'available' : `not available (${ix.environment.simulation.status}: ${ix.environment.simulation.missingClasses.length} runtime classes missing)`, '`cameo_get_simulation_capabilities`'],
  ['Diagram types', `${ix.bridge.diagramTypes} validated types (BDD, IBD, requirement, parametric, activity, …)`, '`cameo_list_diagram_types`'],
  ['Native matrices', ix.bridge.matrixKinds.join(', '), '`cameo_list_matrix_kinds`'],
  ['Java', ix.environment.java, 'system properties'],
  ['Plugins', `${ix.environment.pluginCount} loaded`, 'plugin list']
]);
p('**Confirmed MCP capabilities used:** element creation (packages, blocks, requirements, constraint blocks, properties, ports, activities, actions), relationships (generalization, connector with part-with-port ends, item flow, satisfy, verify, deriveReqt, refine, trace, allocate, control flow), stereotypes and tagged values, diagram creation, shape placement in containers, paths, explicit orthogonal routing, compartments, shape properties, native image export, containment and relationship queries, and guarded Groovy (`cameo_execute_macro`) for value defaults, constraint bodies, colours, item-flow path clean-up and the change profile.', '',
  '**SysML version used — Path C.** The SysML v2 plugin is not installed in this CATIA Magic, and the bridge documents SysML v2 profile support as not implemented. The model is SysML v1 (Cameo SysML plugin) and is never labelled v2. It is structured for migration: part definitions ↔ blocks, part usages ↔ part properties, ports and connectors, item definitions ↔ item blocks, requirements with `satisfy`/`verify`, constraint blocks for calculations, allocations.', '',
  '**Simulation — execution boundary.** Cameo cannot execute the calculation here (no Simulation Toolkit). The architecture, parameters and requirements are authoritative in Cameo; the deterministic calculation runs in GEN7 (`src/engineering/physics.js`); the results are written back into the model as `«testCase»` elements with `«verify»` relationships, and every one of them says it was computed outside Cameo. Nothing claims "Cameo simulated this".', '');

p('## 2. Model built in Cameo', '');
table(['Element kind (UML metaclass)', 'Count in package *AI Factory Cooling System (GEN7)*'], Object.entries(ix.model.counts).map(([k, v]) => [k, int(v)]));
p(`Build: **${int(ix.build.calls)} MCP calls**, ${ix.build.failed} failed and corrected (${ix.build.failures.map(f => f.label).join('; ')}), ${r1(ix.build.ms / 1000)} s of bridge time, including diagram layout iterations. Workflow (demo run): ${ix.workflow.totals.mcpCalls} calls, ${int(ix.workflow.totals.mcpMs)} ms.`, '');
p('Packages: 01 Requirements · 02 Functions · 03 Component Library · 04 System Structure · 05 Loop A v1 · 06 Loop A v2 · 07 Analysis · 08 Verification · 09 Views.', '');

p('### System decomposition', '');
table(['Subsystem', 'Parts'], SYSTEM.subsystems.map(s => [s.name, s.parts.join(', ')]));
p(`Context chain (system-context view): ${CONTEXT.chain.map(([a, z, i]) => `${a} → ${z} (${i})`).join(' · ')}.`, '');

p('### Requirements', '');
table(['Id', 'Name', 'Text', 'Scope'], [['STK-001', 'Future compute density', 'Stakeholder need behind REQ-FUTURE-001', '—'], ...REQUIREMENTS.map(r => [r.id, r.name, r.text, r.scope.join(', ')])]);
p('Relationships: REQ-FUTURE-001 «deriveReqt» STK-001 and the four envelope requirements; Projected Thermal Load «refine» REQ-FUTURE-001; F2 «trace» REQ-FUTURE-001 and «allocate» Loop A; Loop A v1 and v2 «satisfy» the requirements (v2 also REQ-FUTURE-001); test cases «verify» the requirements of their scenario.', '');

for (const id of ['v1', 'v2']) {
  const c = LOOP_A[id];
  p(`### Loop ${id === 'v1' ? 'A v1 — current baseline' : 'A v2 — proposed evolution'}`, '', `Provenance: ${c.provenance}. Control: ${c.params.control}.`, '');
  table(['Tag', 'Element', 'Status vs v1'], c.components.map(x => [x.tag, x.name, x.status + (x.replaces ? ` (replaces ${x.replaces})` : '')]));
}
p('### Exact V1 → V2 changes', '');
table(['Tag', 'Change', 'Status'], st.changes.map(c => [c.tag, c.name + (c.replaces ? ` — replaces ${c.replaces}` : ''), c.status]));
table(['Parameter', 'v1', 'v2'], Object.keys(LOOP_A.v1.params).filter(k => typeof LOOP_A.v1.params[k] === 'number').map(k => [k, LOOP_A.v1.params[k], LOOP_A.v2.params[k]]));
p('### Interfaces affected', '');
table(['Interface', 'Carries', 'Impact of v2'], st.affected.map(a => [a.name, a.flows, a.impact]));

p('## 3. Cameo diagrams (native exports in `evidence/cameo/diagrams/`)', '');
table(['View', 'Cameo diagram type', 'Size', 'File'], Object.values(ix.diagrams).map(d => [d.name, d.diagramType, `${d.width}×${d.height}`, `\`${d.file}\``]));
p('Layout: explicit coordinates and orthogonal routes set through the bridge (no blind auto-layout); duplicate auto-displayed paths removed; colours set through the Cameo API (v2: grey unchanged, amber modified, green added; verification: green pass, amber low margin, red fail).', '');

p('## 4. Engineering basis', '', '### Assumptions', '');
ASSUMPTIONS.forEach(a => p(`- **${a.id}** ${a.text}`)); p('');
p('### Equations', ''); EQUATIONS.forEach(e => p(`- **${e.name}** — \`${e.expr}\` — ${e.note}`)); p('');
p('### Boundary conditions (identical for v1 and v2)', '');
table(['Quantity', 'Value'], [['Facility water supply', `${BOUNDARY.facilityWaterSupplyC} °C`], ['Facility water flow at FW-A', `${BOUNDARY.facilityWaterFlowKgS} kg/s`], ['Coolant', `${FLUIDS.coolant.name}, ${FLUIDS.coolant.densityKgPerL} kg/L, ${FLUIDS.coolant.cpKJPerKgK} kJ/kg·K`], ['Limits', `return ≤ ${LIMITS.maxReturnC} °C · supply ≤ ${LIMITS.maxSupplyC} °C · flow ≥ ${LIMITS.minFlowLpmPerKw} L/min/kW · Δp ≤ ${LIMITS.maxLoopDpKpa} kPa · margin ≥ ${LIMITS.designMarginPct} %`]]);
table(['Scenario', 'Load', 'Basis'], st.scenarios.map(s => [`${s.id} ${s.name}`, `${s.loadKw} kW`, s.basis]));
for (const id of ['v1', 'v2']) {
  const ev = st[id];
  p(`### Results — Loop A ${id} (capacity ${int(ev.capacityKw)} kW, binding: ${limitText(ev.bindingLimit)})`, '');
  table(['Scenario', 'Load', 'Supply / return', 'Flow', 'Δp', 'Pump', 'Margin', 'Result'], ev.scenarios.map(s => [s.id, `${s.loadKw} kW`, `${r1(s.state.supplyC)} / ${r1(s.state.returnC)} °C`, `${int(s.state.flowLpm)} L/min${s.state.flowCapped ? ' (max)' : ''}`, `${int(s.state.dpKpa)} kPa`, `${r1(s.state.pumpKw)} kW`, `${r1(s.marginPct)} %`, s.status + (s.violations.length ? ` — ${s.violations.map(limitText).join(', ')}` : '')]));
}
p('### Comparison', ''); table(['', 'Loop A v1', 'Loop A v2'], st.comparison.map(r => [r.k, r.v1, r.v2]));
p('### Requirement verification matrix (derived)', '');
table(['Requirement', 'v1', 'v2'], st.verification.v1.map((r, i) => [`${r.id} ${r.name}`, `${r.verdict} (${r.value})`, `${st.verification.v2[i].verdict} (${st.verification.v2[i].value})`]));
p('### Trade-offs', ''); st.tradeoffs.forEach(t => p(`- **${t.k}.** ${t.text}`)); p('');
p('### Energy (pumping power only, from the model; no CO₂e — no carbon-intensity assumption provided)', '');
table(['Scenario', 'Load', 'v1 pump', 'v2 pump'], st.energy.map(e => [e.id, `${e.loadKw} kW`, e.v1Kw == null ? 'n/a — v1 fails' : `${r1(e.v1Kw)} kW`, `${r1(e.v2Kw)} kW`]));
p('### Operational options evaluated before the engineering study', '', st.options.rule, '');
table(['Option', 'Action', 'Result', 'Sufficient?'], st.options.list.map(o => [`${o.id} ${o.name}`, o.action, o.result, o.meetsFuture == null ? 'engineering study' : o.meetsFuture ? 'yes' : 'no']));
p(`**${st.options.conclusion}**`, '', `**Conclusion.** ${st.conclusion.v1} ${st.conclusion.v2} The engineer decides: approve for detailed engineering, request additional study, or reject.`, '');
process.stdout.write(L.join('\n') + '\n');
